language: nix

os:
  - linux

before_script:
  - mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
  - mkdir -p ~/.config/nixpkgs

matrix:
  include:
  - env:
    - VERSION=19.09
  - env:
    - VERSION=unstable

script:
  - nix run nixpkgs.haskellPackages.hlint -c hlint src
  - nix build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-$VERSION.tar.gz -f ./release.nix xmonad-masser
