language: nix

os:
  - linux

before_script:
  - mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/$USER
  - mkdir -p ~/.config/nixpkgs

matrix:
  include:
  - env:
    - NIXPKGS=https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz
  - env:
    - NIXPKGS=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz

script:
  - nix run nixpkgs.haskellPackages.hlint -c hlint src
  - nix build -I nixpkgs=$NIXPKGS -f ./release.nix xmonad-masser
