name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [20.09]
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v12
      - run: nix-build -I nixpkgs=channel:nixos-${{ matrix.channel }} -E '(import <nixpkgs> {}).haskellPackages.callPackage ./. {}'
